#! /bin/bash
#
# usage: runtest <PATH_TO_INET_FOLDER> [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE=make

INET_ROOT=$1
TESTFILES=${*:2}
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
EXTRA_INCLUDES=`find ../../../src/ -type d | sed s!^!-I../!`
EXTRA_INCLUDES2=`find $INET_ROOT/src/ -type d | sed s!^!-I!`
opp_test gen $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f --deep -L../../../../lib -linet -L../../../../out/gcc-debug/src -linet_dns_extension -P . --no-deep-includes $EXTRA_INCLUDES $EXTRA_INCLUDES2; $MAKE) || exit 1
echo
opp_test run $OPT -d -v $TESTFILES || exit 1
echo
echo Results can be found in ./work