#!/bin/bash
#
# This shell script runs all tests for the extension.

CURR_DIR=`pwd`
INET_ROOT=$1
failed=0

echo "Running following test directories: ${DIRS}"

find * -prune -type d | while read dir; do
    cd $CURR_DIR/$dir
    ./clean
    echo "********************"
    echo "Executing >> ./runtest ${INET_ROOT} in '${dir}'"
    echo "********************"
    ./runtest $INET_ROOT
    rc=$?
    echo "Executed with exit code: ${rc}"
    if (($rc > 0)); then
       echo
       echo "Test suite failed at '${dir}'"
       failed=$failed+1
    else
      cd ../
      CURR_DIR=`pwd`
      echo "Switched back to ${CURR_DIR}"
      echo
    fi
done

if [ $failed -gt 0 ]; then
  exit 1
fi
