#! /bin/bash
#
# usage: runtest <PATH_TO_INET_FOLDER> [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE=make

INET_ROOT=$1
TESTFILES=${*:2}
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
opp_test gen $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f --deep -L../../../lib -L../../../out/gcc-debug/src -linet -linet_dns_extension -P . --no-deep-includes `find ../../../src/ -type d | sed s!^!-I!` `find $INET_ROOT/src -type d | sed s!^!-I!`; $MAKE) || exit 1
echo
opp_test run $OPT -d -v $TESTFILES -a "--check-signals=false -linet -n \"${INET_ROOT}/src\"" || exit 1
rc=$?
# pass exit code from run..
echo "Exit Code ${rc}"
echo
echo Results can be found in ./work
exit $rc
